### ISSUE TITLE
RHD dataset testing

### ISSUE THREAD

**Issue by nitba** [spurra/vae-hands-3d#13]
Hi @spurra ,
Thanks in advance for your help
For testing `RHD` , assume that we have an image which has two hands, and by using `BinaryDbReader.py` a hand which has more area goes for evaluation,  I mean the other hand is in test image is not assumed for evaluation , am I right? 
from each test image you just pick one hand for  evaluation? and reported results does not assume the all visible joints in test image it just assume the visible joints of just one hand in test image? right?

I consider that  we have 2728 test images in RHD, and you extracted 2728 number for each type joint, it means in each test image with two hands you just tested your algorithm on one hand from that image

**Comment by spurra** [comment]
Hi, regarding which hand gets used for evaluation, check the code from 190 on in BinaryDbReader.py. The more dominant hand in RHD is used for evaluation purposes.
Regarding the visibility of the joint, for evaluation only the visible joints get taken into consideration. This can be seen in line 81-83 in general.py
