### ISSUE TITLE
How many losses you are using for training? 

### ISSUE THREAD

**Issue by biswassanket** [spurra/vae-hands-3d#14]
Can you please mention how many losses you are using for training? Also from your paper I could not understand apart from the MSE loss used for cross reconstruction do you use any self reconstruction (RGB to RGB) loss during training?

**Comment by spurra** [comment]
For each modality, we have one MSE loss and the KL divergence. We have tried the reconstruction loss too (see Table 1, variant 3 and 4). However it didn't improve performance much. It seems to help in the case of semi-supervised training (see Fig. 3)
