### ISSUE TITLE
Training scripts available?

### ISSUE THREAD

**Issue by ghost** [spurra/vae-hands-3d#2]
Hello,
 
I see clearly that evaluation routines are available but the training routines don't seem to be there at first look. Will you possibly make them available in the future so once can train your network with other data?

Thank a lot !

**Comment by spurra** [comment]
The code is a mess and I don't have time to refactor it. Hence I haven't uploaded it. If you want it, you can send me an email and I'll be happy to send it to you. It's spurra + "at" + ethz.ch

**Comment by yunfanLu** [comment]
@spurra Hello, I have sent an E-mail to you.(luyunfan17@mails.ucas.edu.cn) Could you please sent the training scripts for me too. Thank you very much.

**Comment by eris231** [comment]
@spurra Hi I've sent an email to you. (eris205@gmail.com) 
Could you please sent the training scripts for me too? Thank you very much.

**Comment by qq276399331** [comment]
@spurra Hi I've sent an email to you. (18373140341@163.com)
Could you please sent the training scripts for me too? Thank you very much.

**Comment by hakimArfa** [comment]
@spurra Hi I've sent an email to you. (hakim.arfa@he-arc.ch)
Could you please sent the training scripts for me too? Thank you very much.

**Comment by BUPT-ZJie** [comment]
@spurra  Hi I've sent an email to you. (zjie1996@yahoo.com)
Could you please sent the training scripts for me too? Thank you very much.

**Comment by AlexHu123** [comment]
@spurra Hi I've sent an email to you. (alexhu@mail.ustc.edu.cn)
Could you please sent the training scripts for me too? Thank you very much.

**Comment by DavidBoja** [comment]
@spurra Hi, could you please send me the training code as well? I’ve sent you an email.

Thank you in advance and kind regards,
David

**Comment by yunfanLu** [comment]
This is scripts I wrote for training many years ago. Below is the link, hope it helps you.

https://github.com/yunfanLu/VAE-Pose

**Comment by DavidBoja** [comment]
Thanks @yunfanLu , this helps alot!
