### ISSUE TITLE
Why are 3D keypoints not converted to canonical coordinates?

### ISSUE THREAD

**Issue by halcyon370** [spurra/vae-hands-3d#3]
The VAE prediction seems to be compared with data['keypoint_xyz21'], not data['keypoint_xyz21_can']. Is the training of model directly regressing original xyz coordinates? But the ground-truth of 3d keypoints will depend on the position of camera, since each image has its own camera matrices K (e.g. in Rendered Hand Pose Dataset).

**Comment by spurra** [comment]
This is not something we tested, as the performance was adequate enough for the non-canonical coordinates.
