### ISSUE TITLE
Evaluation on Other Datasets

### ISSUE THREAD

**Issue by eris231** [spurra/vae-hands-3d#5]
Hi,

Can you provide some example about how to use your pre-trained model do evaluation on datasets other than RHD and STB?

Thanks

**Comment by ddshan** [comment]
I think that the easiest way to try on your own dataset is to create your dataset of the format just like RHD. I have tried, and it works.

**Comment by spurra** [comment]
Apologies for the late reply. @ddshan is correct, this is indeed the easiest way to go about.

**Comment by calvin422** [comment]
![img](https://user-images.githubusercontent.com/15908970/58750007-3ab3e980-84bf-11e9-8434-bc69a4f7da49.png)

if I just take a photo of it , and no other information provided for example depth and mask, can this model still recognise the hand. If yes, how can I do it? if no, can anyone suggest a model can do it?

thanks
