### ISSUE TITLE
Can we just take a photo and evaluate it ?

### ISSUE THREAD

**Issue by calvin422** [spurra/vae-hands-3d#8]
if I just take any photo  but no other information provided for example depth and mask, can this model still recognise the hand in the photo. If yes, how can I do it? if no, can anyone suggest a model may possible to finish that task?

thanks

![img](https://user-images.githubusercontent.com/15908970/58750058-d5acc380-84bf-11e9-9e70-ea0e6a13f61e.png)

**Comment by spurra** [comment]
Yes you can, provided you crop it before hand. If you do not crop it, the performance will be bad.

**Comment by calvin422** [comment]
May I know what step should I do for evaluating this picture ?
1. where do the picture put? put it in the RHD_published_v2
2. what is the step? need to run create_binary_db.py and then evaluate_model.py?

**Comment by spurra** [comment]
You load the trained model and its definition which can be found here: https://ait.ethz.ch/projects/2018/vae_hands/downloads/models.zip

After loading it, you input your cropped image into the RGB encoder. This will give you a latent code sample. This sample you can then feed into the 3d joint decoder which will give you the 3d pose.
